# GLOBAL SETTINGS
title           : !!str Arcadia
description     : !!str Arcadia is a website that presents several scenarios for installing Arch Linux on LUKS
baseurl         : !!str "/Arcadia"
github_username : !!str ChaosDynamix

# THEME SETTINGS
remote_theme    : !!str pmarsceill/just-the-docs
search_enabled  : !!bool false
aux_links       : !!map
    "Github": !!seq
        - "//github.com/ChaosDynamix/Arcadia"

# MARKDOWN SETTINGS
markdown  : !!str kramdown
kramdown  : !!map
    toc_levels              : "2"
    syntax_highlighter_opts : !!map
        default_lang  : !!str bash

# EXCLUDE
exclude: !!seq
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor
    - Makefile
    - README.md

# DEFAULTS
defaults: !!seq

    - !!map         # LOGICAL VOLUME MANAGER
        scope         : !!map
            path    : !!str "_guide/system/lvm"
        values        : !!map
            layout  : !!str default
            context : !!str lvm

    - !!map         # DESKTOP ENVIRONMENT
        scope         : !!map
            path    : !!str "_guide/gui/de"
        values        : !!map
            layout  : !!str default
            context : !!str de

    - !!map         # WINDOW MANAGER
        scope         : !!map
            path    : !!str "_guide/gui/wm"
        values        : !!map
            layout  : !!str default
            context : !!str wm
