# GLOBAL SETTINGS
title           : !!str Arcadia
description     : !!str Arcadia is a website that presents a personal guide for installing Arch Linux on LUKS and UEFI
baseurl         : !!str "/Arcadia"
github_username : !!str ChaosDynamix

# THEME SETTINGS
remote_theme   : !!str pmarsceill/just-the-docs
search_enabled : !!bool false
aux_links      : !!map
  "Github": !!seq
    - "//github.com/ChaosDynamix/Arcadia"

# MARKDOWN SETTINGS
markdown : !!str kramdown
kramdown : !!map
  toc_levels              : "2"
  syntax_highlighter_opts : !!map
    default_lang : !!str bash

# EXCLUDE
exclude : !!seq
  - Gemfile
  - Gemfile.lock
  - README.md
  - Dockerfile
  - docker-compose.yml
  - package.json
  - package-lock.json
  - node_modules
  - vendor

# DEFAULTS
defaults : !!seq

  - !!map
    scope  : !!map
      path   : !!str "guide/"
    values : !!map
      layout : !!str default
