# GLOBAL SETTINGS
title           : !!str Andromeda
description     : !!str Andromeda is one of the many guides to install and configure Arch Linux.
baseurl         : !!str "/Andromeda"
github_username : !!str ChaosDynamix

# THEME SETTINGS
remote_theme    : !!str pmarsceill/just-the-docs
footer_content  : !!str "Copyright &copy; 2020 ChaosDynamix."
search_enabled  : !!bool true
aux_links       : !!map
  "Github": !!seq
    - "//github.com/ChaosDynamix/Andromeda"

# MARKDOWN SETTINGS
markdown  : !!str kramdown
kramdown  : !!map
  toc_levels              : "2"
  syntax_highlighter_opts : !!map
    default_lang  : !!str bash

# EXCLUDE
exclude: !!seq
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - Makefile
  - README.md

# COLLECTIONS
collections : !!map

  # DOCUMENTATION
  documentation : !!map
    uuid      : !!str a5e4be81-7697-4061-9553-6ad752e4965d
    output    : !!bool true
    permalink : !!str /:collection/:path

# DEFAULTS
defaults: !!seq

  - !!map     # LOGICAL VOLUME MANAGER
    scope   : !!map
      path  : !!str "_documentation/system/lvm"
    values  : !!map
      layout        : !!str default
      context_uuid  : !!str 94854e83-3816-42e4-8d5f-f48d3a54483e
      context_abbr  : !!str LVM

  - !!map     # B TREE FILESYSTEM
    scope   : !!map
      path  : !!str "_documentation/system/btrfs"
    values  : !!map
      layout        : !!str default
      context_uuid  : !!str 80a79960-1e97-479e-8d0e-789516293fc0
      context_abbr  : !!str BTRFS

  - !!map     # DESKTOP ENVIRONMENT
    scope   : !!map
      path  : !!str "_documentation/gui/de"
    values  : !!map
      layout        : !!str default
      context_uuid  : !!str 9e55133c-c83d-43fb-9386-af81ef91b6dc
      context_abbr  : !!str DE

  - !!map     # WINDOW MANAGER
    scope   : !!map
      path  : !!str "_documentation/gui/wm"
    values  : !!map
      layout        : !!str default
      context_uuid  : !!str 83bc464a-a758-4b5c-a83b-65e92548c5c6
      context_abbr  : !!str WM
