# Global settings
title: Andromeda
email: your-email@example.com
description: Andromeda is one of the many guides to install and configure Arch Linux.
baseurl: "/Andromeda"
url: ""
github_username:  ChaosDynamix
footer_content: "Copyright &copy; 2020 ChaosDynamix."

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

# Auxiliary links
aux_links:
  "Home":
    - "//chaosdynamix.github.io/Andromeda"
  "Github":
    - "//github.com/ChaosDynamix/Andromeda"

# Kramdown
kramdown:
  toc_levels: "2"
  syntax_highlighter_opts:
    default_lang: bash

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - Makefile
  - README.md

# Collections_dir
collections_dir: _docs

# Collections
collections:

  installation:
    title: installation
    output: true
    permalink: /:collection/:path
    nav_include: true
    nav_order: 1
    sections:
      - name: lvm
        nav_order: 1
      - name: btrfs
        nav_order: 2

  desktop:
    title: desktop
    output: true
    permalink: /:collection/:path
    nav_include: true
    nav_order: 2
    sections:
      - name: desktop environment
        nav_order: 1
      - name: window manager
        nav_order: 2

  library:
    title: library
    output: true
    permalink: /:collection/:path
    nav_include: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      nav_exclude: true
      search_exclude: true
  -
    scope:
      path: "_docs/_installation/lvm"
    values:
      layout: default
      section: lvm
  -
    scope:
      path: "_docs/_installation/btrfs"
    values:
      layout: default
      section: btrfs
  -
    scope:
      path: "_docs/_desktop/desktop-environment"
    values:
      layout: default
      section: desktop environment
  -
    scope:
      path: "_docs/_desktop/window-manager"
    values:
      layout: default
      section: window manager
  -
    scope:
      path: "_docs/_library"
    values:
      layout: default
