# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andromeda
email: your-email@example.com
description: Andromeda is one of the many guides to install and configure Arch Linux.
baseurl: "/Andromeda" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ChaosDynamix

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

# Auxiliary links
aux_links:
  "Home":
    - "//chaosdynamix.github.io/Andromeda"
  "Github":
    - "//github.com/ChaosDynamix/Andromeda"

# Kramdown
kramdown:
  toc_levels: "2"
  syntax_highlighter_opts:
    default_lang: bash

# Collections_dir
collections_dir: _docs

# Collections
collections:

  preparation:
    title: Preparation
    nav_order: 1
    permalink: /:collection/:path/
    has_sections: true
    output: true
    is_post: false
    sections:
      - name: Installation image
        nav_order: 1
      - name: Installation media
        nav_order: 2

  live-environment:
    title: Live environment
    nav_order: 2
    permalink: /:collection/:path/
    has_sections: false
    output: true
    is_post: false

  installation:
    title: Installation
    nav_order: 3
    permalink: /:collection/:path/
    has_sections: true
    output: true
    is_post: false
    sections:
      - name: Logical Volume Manager
        nav_order: 1

  configuration:
    title: Configuration
    nav_order: 4
    permalink: /:collection/:path/
    has_sections: false
    output: true
    is_post: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
