# Global settings
title: Andromeda
email: your-email@example.com
description: Andromeda is one of the many guides to install and configure Arch Linux.
baseurl: "/Andromeda"
url: ""
github_username:  ChaosDynamix
footer_content: "Copyright &copy; 2020 ChaosDynamix."

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

# Auxiliary links
aux_links:
  "Home":
    - "//chaosdynamix.github.io/Andromeda"
  "Github":
    - "//github.com/ChaosDynamix/Andromeda"

# Kramdown
kramdown:
  toc_levels: "2"
  syntax_highlighter_opts:
    default_lang: bash

# Defaults
defaults:
  -
    scope:
      path: "_docs/_stage1/lvm"
    values:
      layout: default
      section: lvm
  -
    scope:
      path: "_docs/_stage1/btrfs"
    values:
      layout: default
      section: btrfs
  -
    scope:
      path: "_docs/_stage2/desktop-environment"
    values:
      layout: default
      section: desktop environment
  -
    scope:
      path: "_docs/_stage2/window-manager"
    values:
      layout: default
      section: window manager

# Collections_dir
collections_dir: _docs

# Collections
collections:

  stage1:
    title: Stage 1
    nav_order: 1
    permalink: /:collection/:path/
    output: true
    is_post: false
    sections:
      - name: lvm
        nav_order: 1
      - name: btrfs
        nav_order: 2

  stage2:
    title: Stage 2
    nav_order: 2
    permalink: /:collection/:path/
    output: true
    is_post: false
    sections:
      - name: desktop environment
        nav_order: 1
      - name: window manager
        nav_order: 2

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - Makefile
  - README.md
