# Global settings
title: Andromeda
email: your-email@example.com
description: Andromeda is one of the many guides to install and configure Arch Linux.
baseurl: "/Andromeda"
url: ""
github_username:  ChaosDynamix

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

# Auxiliary links
aux_links:
  "Home":
    - "//chaosdynamix.github.io/Andromeda"
  "Github":
    - "//github.com/ChaosDynamix/Andromeda"

# Kramdown
kramdown:
  toc_levels: "2"
  syntax_highlighter_opts:
    default_lang: bash

# Defaults
defaults:
  -
    scope:
      path: "_docs/_preparation"
    values:
      layout: default
  -
    scope:
      path: "_docs/_scenario/lvm"
    values:
      layout: default
      section: lvm
  -
    scope:
      path: "_docs/_display"
    values:
      layout: default
  -
    scope:
      path: "_docs/_gui/desktop-environment"
    values:
      layout: default
      section: desktop environment
  -
    scope:
      path: "_docs/_gui/window-manager"
    values:
      layout: default
      section: window manager

# Collections_dir
collections_dir: _docs

# Collections
collections:

  preparation:
    title: Preparation
    nav_order: 1
    permalink: /:collection/:path/
    output: true
    is_post: false
    has_sections: false

  scenario:
    title: Scenario
    nav_order: 2
    permalink: /:collection/:path/
    output: true
    is_post: false
    has_sections: true
    sections:
      - name: lvm
        nav_order: 1

  display:
    title: Display
    nav_order: 3
    permalink: /:collection/:path/
    output: true
    is_post: false
    has_sections: false

  gui:
    title: Graphical user interface
    nav_order: 4
    permalink: /:collection/:path/
    output: true
    is_post: false
    has_sections: true
    sections:
      - name: desktop environment
        nav_order: 1
      - name: window manager
        nav_order: 2
