version  : !!str 3.8
services : !!map

  jekyll  : !!map
    image       : !!str ruby:latest
    working_dir : !!str /usr/src/app
    ports       : !!seq
      - !!str 4000:4000
    volumes     : !!seq
      - !!str ./:/usr/src/app
      - !!str ./vendor/bundle:/usr/local/bundle
    command     : !!str >
      bash -c "bundle install &&
               bundle exec jekyll serve --host 0.0.0.0 --port 4000"

  webpack : !!map
    image       : !!str node:alpine
    user        : !!str node
    working_dir : !!str /home/node/app
    environment : !!seq
      - !!str NODE_ENV=development
    volumes     : !!seq
      - !!str ./:/home/node/app
    command     : !!str ls
